apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: qdrant
spec:
  storageClassName: crc-csi-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-local
  namespace: qdrant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: vector-store
  template:
    metadata:
      labels:
        app: vector-store
    spec:
      serviceAccountName: qdrant-sa
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 6333
            - name: grpc
              containerPort: 6334
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: QDRANT__SERVICE__API_KEY
              value: "d30472a4-517f-4422-895e-90b21c897708"
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
              subPath: storage
            - name: qdrant-storage
              mountPath: /qdrant/snapshots
              subPath: snapshots
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-svc
  namespace: qdrant
spec:
  type: NodePort
  selector:
    app: vector-store
  ports:
    - name: api
      port: 6333
      targetPort: 6333
      nodePort: 30001
    - name: grpc
      port: 6334
      targetPort: 6334
      nodePort: 30002
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrant-sa
  namespace: qdrant
